app = "quran-discord-bot1"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"

[processes]
  app = "node index.js"

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running =
